"""Pydantic schemas for API request and response bodies."""

from app.schemas.ai_assistant import (
    AiStatusResponse,
    ClientSummaryDraftRequest,
    DraftReplyRequest,
    DraftReplyResponse,
    EmailActionItemsRequest,
    EmailActionItemsResponse,
    EmailSummaryRequest,
    EmailSummaryResponse,
    ExtractFileLinksRequest,
    ExtractFileLinksResponse,
    MaintenanceRecommendationDraftRequest,
    ReportSectionDraftRequest,
    ReportSectionDraftResponse,
    SuggestRecordLinksRequest,
    SuggestRecordLinksResponse,
)
from app.schemas.ai_draft import AiDraftCreate, AiDraftListResponse, AiDraftRead, AiDraftUpdate
from app.schemas.client import ClientBase, ClientCreate, ClientListResponse, ClientRead, ClientUpdate
from app.schemas.email_import_batch import (
    EmailImportBatchBase,
    EmailImportBatchCreate,
    EmailImportBatchListResponse,
    EmailImportBatchRead,
)
from app.schemas.email_message import (
    EmailMessageBase,
    EmailMessageCreate,
    EmailMessageListResponse,
    EmailMessageRead,
    EmailMessageUpdate,
)
from app.schemas.email_record_link import (
    EmailRecordLinkBase,
    EmailRecordLinkCreate,
    EmailRecordLinkListResponse,
    EmailRecordLinkRead,
)
from app.schemas.evidence_file import (
    EvidenceFileBase,
    EvidenceFileCreate,
    EvidenceFileListResponse,
    EvidenceFileRead,
    EvidenceFileUpdate,
)
from app.schemas.job import JobBase, JobCreate, JobListResponse, JobRead, JobUpdate
from app.schemas.integration_status import IntegrationProviderStatus, IntegrationsStatusResponse
from app.schemas.outlook_import import (
    OutlookImportSelectedRequest,
    OutlookImportSelectedResponse,
    OutlookPreviewMessage,
    OutlookPreviewRequest,
    OutlookPreviewResponse,
    OutlookStatusResponse,
)
from app.schemas.outlook_auth import (
    OutlookAuthCallbackResponse,
    OutlookAuthStartResponse,
    OutlookAuthStatusResponse,
    OutlookDisconnectRequest,
    OutlookDisconnectResponse,
)
from app.schemas.outlook_draft import (
    OutlookDraftFromAiDraftRequest,
    OutlookDraftFromAiDraftResponse,
)
from app.schemas.reminder import (
    ReminderBase,
    ReminderCreate,
    ReminderListResponse,
    ReminderRead,
    ReminderUpdate,
)
from app.schemas.report_readiness import (
    ReportReadinessCheck,
    ReportReadinessResponse,
)
from app.schemas.site import (
    SiteBase,
    SiteCreate,
    SiteListResponse,
    SiteMapListResponse,
    SiteMapRead,
    SiteRead,
    SiteUpdate,
)
from app.schemas.timeline import TimelineEntry, TimelineListResponse

__all__ = [
    "AiStatusResponse",
    "AiDraftCreate",
    "AiDraftListResponse",
    "AiDraftRead",
    "AiDraftUpdate",
    "ClientSummaryDraftRequest",
    "ClientBase",
    "ClientCreate",
    "ClientListResponse",
    "ClientRead",
    "ClientUpdate",
    "EmailImportBatchBase",
    "EmailImportBatchCreate",
    "EmailImportBatchListResponse",
    "EmailImportBatchRead",
    "DraftReplyRequest",
    "DraftReplyResponse",
    "EmailActionItemsRequest",
    "EmailActionItemsResponse",
    "EmailMessageBase",
    "EmailMessageCreate",
    "EmailMessageListResponse",
    "EmailMessageRead",
    "EmailMessageUpdate",
    "EmailRecordLinkBase",
    "EmailRecordLinkCreate",
    "EmailRecordLinkListResponse",
    "EmailRecordLinkRead",
    "EmailSummaryRequest",
    "EmailSummaryResponse",
    "EvidenceFileBase",
    "EvidenceFileCreate",
    "EvidenceFileListResponse",
    "EvidenceFileRead",
    "EvidenceFileUpdate",
    "ExtractFileLinksRequest",
    "ExtractFileLinksResponse",
    "IntegrationProviderStatus",
    "IntegrationsStatusResponse",
    "JobBase",
    "JobCreate",
    "JobListResponse",
    "JobRead",
    "JobUpdate",
    "MaintenanceRecommendationDraftRequest",
    "OutlookAuthCallbackResponse",
    "OutlookAuthStartResponse",
    "OutlookAuthStatusResponse",
    "OutlookDisconnectRequest",
    "OutlookDisconnectResponse",
    "OutlookDraftFromAiDraftRequest",
    "OutlookDraftFromAiDraftResponse",
    "OutlookImportSelectedRequest",
    "OutlookImportSelectedResponse",
    "OutlookPreviewMessage",
    "OutlookPreviewRequest",
    "OutlookPreviewResponse",
    "OutlookStatusResponse",
    "ReminderBase",
    "ReminderCreate",
    "ReminderListResponse",
    "ReminderRead",
    "ReminderUpdate",
    "ReportReadinessCheck",
    "ReportReadinessResponse",
    "ReportSectionDraftRequest",
    "ReportSectionDraftResponse",
    "SiteBase",
    "SiteCreate",
    "SiteListResponse",
    "SiteMapListResponse",
    "SiteMapRead",
    "SiteRead",
    "SiteUpdate",
    "SuggestRecordLinksRequest",
    "SuggestRecordLinksResponse",
    "TimelineEntry",
    "TimelineListResponse",
]
